name: test
run-name: ${{ github.actor }} - test
on: [pull_request, push]
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - uses: actions/setup-node@v3
        with:
          node-version: '18.17.0'

      - run: node --version
      - run: npm --version

      - run: npm ci

      - run: npm run test

      - run: |
          echo "cleanup ...."
          git clean -fdx .
          git checkout -f
          git submodule foreach 'git clean -fdx .'
          git submodule foreach 'git checkout -f'
      
      - run: |
          rm package-lock.json

      - run: |
          npm i
          npm run test

      # - name: Upload Artifact
      #   uses: actions/upload-artifact@v3
      #   with: 
      #     name: ${{ matrix.os }}
      #     path: test/build-engine
